language: java
jdk:
  - oraclejdk7
before_install:
 - chmod +x gradlew
 - travis setup releases
script: ./gradlew build
deploy:
  provider: releases
  file: "/build/*.jar"
  skip_cleanup: true
  on:
    all_branches: true
