language: java
jdk:
  - oraclejdk7
install:
  - sudo apt-get update -y
  - chmod +x ./gradlew
script:
  -
  - ./gradlew build
before-deploy:
  - "echo ACCOUNT"
  - echo ACCOUNT
  - echo 'ACCOUNT'
deploy:
  provider: releases
  user: 
    - secure: ACCOUNT
  password:
    - secure: PASS
  file: /build/libs/*.jar
  skip_cleanup: true
  on:
    branch: release
