language: java
jdk:
  - oraclejdk7
install:
  - sudo apt-get update -y
  - chmod +x ./gradlew
script:
  - ./gradlew build
before_deploy:
  - cd build
  - zip -r build.zip .
deploy:
  provider: releases
  api_key:
    secure: LxQqAjOSnysclLySZo8sG+diXTEfoGBs8AKMKZn6W/PLwtpv+kJRJIOYlyCezfJ4S0C82s0bt0bcSSOIKRhy/yII42v7+VdD7xD0AGNa5Nrgkg6ju6HCkV4zszQo1afHj9qhHOPkl2oVuWUFs6eDMU5geZfQGRHhruTmNJOKIZk=
  file: /build/build.zip
  skip_cleanup: true
  on:
    all_branches: true
