language: java
jdk:
  - oraclejdk7
install:
  - sudo apt-get update -y
  - chmod +x ./gradlew
script:
  - ./gradlew build
before_deploy:
  - cd build
  - zip -r build.zip .
deploy:
  provider: releases
  api-key:
    secure: "eXdZ/6j42d4PkeIk/9EPv18mrO9kj74t//N6xlkpnwymzS+lA4bpHYKL6s4iC0GZS/oUhcXZygmPVJQpTeaY0pXGFoMjcTgCHEMW8NO/JhKC/LSekDOagz6d7rcxoTFkVN1IMEH1H5ZvLnytfKJ1qD69bziyA+9O0iVObyjNKfo="
  file: /build/build.zip
  skip_cleanup: true
  on:
    all_branches: true
