language: java
jdk:
  - oraclejdk7
install:
  - sudo apt-get update -y
  - chmod +x ./gradlew
script:
  - ./gradlew build
before_deploy:
  - cd build
  - zip -r build.zip .
deploy:
  provider: releases
  user: ACCOUNT
  password: PASS
  file: /build/build.zip
  skip_cleanup: true
  on:
    branch: release
