language: java
jdk:
  - oraclejdk7
before_install:
 - chmod +x gradlew
script: ./gradlew build
deploy:
  provider: releases
  file: "/build/*.jar"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
