language: java
jdk:
  - oraclejdk7
before_install:
 - chmod +x gradlew
script: ./gradlew build
deploy:
  provider: releases
  file: "/build/*.jar"
  api-key: AUTHKEY
  skip_cleanup: true
  on:
    all_branches: true
